
	<footer>
		<div class="menu">
			<div class="section">
				<div class="header">Учням</div>
				<div class="items">
					<a class="item" href="/" title="">Допомога</a>
					<a class="item" href="/" title="">Часті питання</a>
					<a class="item" href="/" title="">Вартість</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Викладачам</div>
				<div class="items">
					<a class="item" href="/" title="">Допомога</a>
					<a class="item" href="/" title="">Часті питання</a>
					<a class="item" href="/" title="">Вартість</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Про lingva.ua</div>
				<div class="items">
					<a class="item" href="/" title="">Хто ми є</a>
					<a class="item" href="/" title="">Користувачі</a>
					<a class="item" href="/" title="">Партнери</a>
					<a class="item" href="/" title="">Контакти</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Проекти</div>
				<div class="items">
					<a class="item" href="http://skillsacademy.com.ua/" title="">Skills Academy</a>
					<a class="item" href="/">Lingva Class</a>
					<a class="item" href="/" title="">Блог</a>
				</div>
			</div>
		</div>
		<div class="license">
			<div class="terms"><a href="/" title="Умови використання інформації, розміщеної на веб-майданчиках компанії">Умови використання</a></div>
			<div class="copyright"><span title="Всі права захищені">&copy; 2016 — 2017</span> <a href="https://lingva.ua/" title="">lingva.ua</a></div>
		</div>
	</footer>
