
	<footer>
		<div class="menu">
			<div class="section">
				<div class="header">Про нас</div>
				<div class="items">
					<a class="item" href="/" title="">Хто ми є</a>
					<a class="item" href="/" title="">Клієнти</a>
					<a class="item" href="/" title="">Контакти</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Допомога</div>
				<div class="items">
					<a class="item" href="/" title="">Часті питання</a>
					<a class="item" href="/" title="">Форум</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Проекти</div>
				<div class="items">
					<a class="item" href="/" title="">Курси</a>
					<a class="item" href="/">Навчання у групі</a>
					<a class="item" href="/" title="">Блог</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Послуги</div>
				<div class="items">
					<a class="item" href="">2</a>
				</div>
			</div>
		</div>
		<div class="license">
			<div class="terms"><a href="/" title="Умови використання інформації, розміщеної на веб-майданчиках компанії">Умови використання</a></div>
			<div class="copyright"><span title="Всі права захищені">&copy; 2016 — 2017</span> <a href="https://lingva.ua/" title="">lingva.ua</a></div>
		</div>
	</footer>
