			<div class="main-menu-container">
				<div class="sections">
					<div class="section" data-group-id="1">
						<div class="section-name">Користувачу</div>
						<div class="items">
							<div class="item link"><a class="link" title="" href="/ukrlingva-login.html">Увійти</a></div>
							<div class="item link"><a class="link" title="" href="/ukrlingva-registration.html">Зареєструватися</a></div>
						</div>
					</div>
					<div class="section" data-group-id="2">
						<div class="section-name">Учням</div>
						<div class="items">
							<div class="item link"><a class="link" title="" href="/">Курси</a></div>
							<div class="item link"><a class="link" title="" href="/">Допомога</a></div>
							<div class="item link"><a class="link" title="" href="/">Часті питанняЧасті питанняЧасті питанняЧасті питання</a></div>
							<div class="item link"><a class="link" title="" href="/">Вартість</a></div>
						</div>
					</div>
					<div class="section" data-group-id="3">
						<div class="section-name">Про укрлінгва</div>
						<div class="items">
							<div class="item link"><a class="link" title="" href="/">Хто ми є</a></div>
							<div class="item link"><a class="link" title="" href="/">Користувачі Користувачі</a></div>
							<div class="item link"><a class="link" title="" href="/">Партнери</a></div>
							<div class="item link"><a class="link" title="" href="/">Контакти</a></div>
						</div>
					</div>
				</div>
			</div>
