			<div class="user-dictionary-menu-container">
				<div class="items">
					<div class="item difficult">
						<div>Difficult</div>
						<div class="amount">25</div>
					</div>
					<div class="item in-process">
						<div>Study</div>
						<div class="amount">225</div>
					</div>
					<div class="item in-memory">
						<div>Memorized</div>
						<div class="amount">405</div>
					</div>
				</div>
			</div>
