			<div class="main-menu-container">
				<div class="sections">
					<div class="section">
						<div class="section-name user">
							<div class="user-avatar image" data-background-image-url="/img/photo.jpg"></div>
							<div class="user-name">Андрій Красоткін aka shain</div>
						</div>
						<div class="items">
							<div class="item link"><a class="link" title="" href="/">Панель</a></div>
							<div class="item link"><a class="link" title="" href="/">Обліковий запис</a></div>
							<div class="item link"><a class="link" title="" href="/">Налаштування</a></div>
							<div class="item link"><a class="link" title="" href="/">Надіслати відгук</a></div>
							<div class="item link"><a class="link" title="" href="/">Вийти</a></div>
						</div>
					</div>
					<div class="section">
						<div class="section-name">Учням</div>
						<div class="items">
							<div class="item link"><a class="link" title="" href="/">Курси</a></div>
							<div class="item link"><a class="link" title="" href="/">Допомога</a></div>
							<div class="item link"><a class="link" title="" href="/">Часті питанняЧасті питанняЧасті питанняЧасті питання</a></div>
							<div class="item link"><a class="link" title="" href="/">Вартість</a></div>
						</div>
					</div>
					<div class="section">
						<div class="section-name">Про укрлінгва</div>
						<div class="items">
							<div class="item link"><a class="link" title="" href="/">Хто ми є</a></div>
							<div class="item link"><a class="link" title="" href="/">Користувачі Користувачі</a></div>
							<div class="item link"><a class="link" title="" href="/">Партнери</a></div>
							<div class="item link"><a class="link" title="" href="/">Контакти</a></div>
						</div>
					</div>
				</div>
			</div>
